version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_name
      DATABASE_HOST: 127.0.0.1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "3307:8080"

  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    env_file:
      - backend/.env

volumes:
  mysql_data:
