version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: database_name
      DATABASE_HOST: 127.0.0.1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --init-file /docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
